models/Animales.php
<?php

namespace app\models;

/**
 * This is the model class for table "animales".
 *
 * @property int $id
 * @property int $especie_id
 * @property string $nombre
 * @property string $nacimiento
 * @property string $defuncion
 * @property string $chip
 * @property string $peso
 * @property bool $ppp
 * @property bool $esterilizado
 * @property string $sexo
 * @property string $observaciones
 * @property string $created_at
 * @property string $updated_at
 *
 * @property Acogidas[] $acogidas
 * @property AnimalesColores[] $animalesColores
 * @property Colores[] $colors
 * @property AnimalesEnfermedades[] $animalesEnfermedades
 * @property AnimalesRazas[] $animalesRazas
 * @property Razas[] $razas
 */
class Animales extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'animales';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nombre', 'especie_id'], 'required'],
            [[
                'nombre',
                'chip',
                'peso',
                'nacimiento',
                'defuncion',
                'sexo',
                'chip',
                'ppp',
                'observaciones',
            ], 'trim'],

            [[
                'chip',
                'sexo',
                'chip',
            ], 'filter', 'filter' => 'strtolower'],
            [[
                'nombre',
                'chip',
                'nacimiento',
                'defuncion',
                'sexo',
                'chip',
            ], 'filter', 'filter' => function ($value) {
                return str_replace('.', '', $value);
            }],
            [['sexo'], 'match', 'pattern' => '/^[h|m]{1}$/'],
            [['nacimiento', 'chip', 'peso', 'sexo'], 'default', 'value' => null],
            [['peso'], 'number', 'min' => 0, 'max' => 9999],
            [['ppp', 'esterilizado'], 'boolean'],
            [['observaciones'], 'string'],
            [['nombre', 'chip', 'defuncion'], 'string', 'max' => 255],
            [['sexo'], 'string', 'max' => 6],
            [['chip'], 'unique'],
            [['especie_id'], 'integer'],
            [['especie_id'], 'exist', 'skipOnError' => true, 'targetClass' => Especies::className(), 'targetAttribute' => ['especie_id' => 'id']],
            ['especie_id', function ($attribute, $params, $validator) {
                $razasDiscordantes = AnimalesRazas::find()->joinWith('raza')->where(['animal_id' => $this->id])->andWhere(['<>', 'especie_id', $this->especie_id])->all();
                foreach ($razasDiscordantes as $animal_raza) {
                    $animal_raza->delete();
                }
            }],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'nacimiento' => 'Nacimiento',
            'chip' => 'Chip',
            'peso' => 'Peso',
            'ppp' => 'PPP',
            'esterilizado' => 'Esterilizado',
            'sexo' => 'Sexo',
            'especie_id' => 'Especie',
            'observaciones' => 'Observaciones',
            'defuncion' => 'Fecha defunción',
            'created_at' => 'Fecha Creación',
            'updated_at' => 'Última modificación',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEspecie()
    {
        return $this->hasOne(Especies::className(), ['id' => 'especie_id'])->inverseOf('animales');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTratamientos()
    {
        return $this->hasMany(Tratamientos::className(), ['animal_id' => 'id'])->inverseOf('animal');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMedicamentos()
    {
        return $this->hasMany(Medicamentos::className(), ['id' => 'medicamento_id'])->viaTable('tratamientos', ['animal_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAcogidas()
    {
        return $this->hasMany(Acogidas::className(), ['animal_id' => 'id'])->inverseOf('animal');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAnimalesColores()
    {
        return $this->hasMany(AnimalesColores::className(), ['animal_id' => 'id'])->inverseOf('animal');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getColors()
    {
        return $this->hasMany(Colores::className(), ['id' => 'color_id'])->viaTable('animales_colores', ['animal_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAnimalesEnfermedades()
    {
        return $this->hasMany(AnimalesEnfermedades::className(), ['animal_id' => 'id'])->inverseOf('animal')->orderBy('desde', 'ASC');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAnimalesRazas()
    {
        return $this->hasMany(AnimalesRazas::className(), ['animal_id' => 'id'])->inverseOf('animal');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRazas()
    {
        return $this->hasMany(Razas::className(), ['id' => 'raza_id'])->viaTable('animales_razas', ['animal_id' => 'id']);
    }

    /**
     * sexos disponibles de un animal
     * @return array los sexos disponibles.
     */
    public function sexosDisponibles()
    {
        return [
            '' => '',
            'h' => 'HEMBRA',
            'm' => 'MACHO',
        ];
    }

    /**
    * Colores que no tiene el animal
    * @return array Array con los modelos de razas.
    */

    public function getColoresQueNoTengo()
    {
        // if (!isset($this->sintomasQueNoTengo)) {
        //     return $this->sintomasQueNoTengo;
        // }
        $sql = <<<'EOT'
select *
  from colores
except
select colores.*
  from colores
  join animales_colores
    on colores.id = animales_colores.color_id
 where animales_colores.animal_id = :animal_id
EOT;
        return Colores::findBySql($sql, [':animal_id' => $this->id])->all();
    }

    /**
    * Razas a las que no pertenece el animal
    * @return array Array con los modelos de razas.
    */

    public function getRazasQueNoTengo()
    {
        // if (!isset($this->sintomasQueNoTengo)) {
        //     return $this->sintomasQueNoTengo;
        // }
        $sql = <<<'EOT'
select *
  from Razas
where especie_id = :especie_id
except
select Razas.*
  from razas
  join animales_razas
    on razas.id = animales_razas.raza_id
 where animales_razas.animal_id = :animal_id
   and especie_id = :especie_id
EOT;
        return Razas::findBySql($sql, [':animal_id' => $this->id, ':especie_id' => $this->especie_id])->all();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVacunaciones()
    {
        return $this->hasMany(Vacunaciones::className(), ['animal_id' => 'id'])->inverseOf('animal')->orderBy('vacunaciones.fecha');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVacunas()
    {
        return $this->hasMany(Vacunas::className(), ['id' => 'medicamento_id'])->viaTable('vacunaciones', ['animal_id' => 'id'])->orderBy('vacunas.vacuna');
    }
}

controllers/EspeciesController.php
<?php

namespace app\controllers;

use app\models\Especies;
use app\models\EspeciesSearch;
use Yii;
use yii\web\NotFoundHttpException;

/**
 * EspeciesController implements the CRUD actions for Especies model.
 */
class EspeciesController extends ControllerControlAccess
{
    /**
     * Lists all Especies models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EspeciesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Especies model.
     * @param int $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Especies model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Especies();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Especies model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Especies model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Especies model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id
     * @return Especies the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Especies::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/especies/_detalle.php
<?php
use yii\helpers\Html;
?>
<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading<?= $model->id?>">
        <h4 class="panel-title">
            <div class="row">
                <div class="col-sm-6">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<?= $model->id?>" aria-expanded="true" aria-controls="collapse">
                            <?= $model->especie ?>
                    </a>
                </div>
                <div class="col-sm-6" style="text-align: right">
                    <?= Html::a('Actualizar', ['update', 'id' => $model->id], ['class' => 'btn btn-xs btn-primary']) ?>
                    <?= Html::a('Borrar', ['delete', 'id' => $model->id], [
                        'class' => 'btn btn-xs btn-danger',
                        'data' => [
                            'confirm' => "¡IMPORTANTE! \n\nSi lo borras se borraran todas las razas que contenga.\n\n¿Estas seguro de que quieres borrar este elemento?\n\n",
                            'method' => 'post',
                        ],
                    ]) ?>
                </div>
            </div>
        </h4>
    </div>
    <div id="collapse<?= $model->id?>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<?= $model->id?>">
        <div class="panel-body">
            <?= Html::beginForm(['razas/create'], 'post') ?>
            <div class="row">
                  <div class="col-lg-6">
                    <div class="input-group">
                      <?= Html::input('text', 'raza', null, [
                          'id' => "input-{$model->id}",
                          'class' => 'form-control',
                          'data' => [
                              'enfermedad' => $model->id ,
                          ],
                          'placeholder'=>"Registra una nueva raza en esta especie ({$model->especie})",
                          'required' => 'true',
                          ]) ?>
                          <span class="input-group-btn">
                              <button value="<?= $model->id ?>" class="btn btn-default registrar-raza" type="submit">¡Registrar!</button>
                          </span>
                    </div>
                </div>
            </div>
            <?= Html::endForm() ?>
            <div class="error-<?= $model->id ?>">
            </div>
            <div class="razas-<?= $model->id ?>">
                <?= $this->render('/razas/_listaRazas', [
                    'items' => $model->razas,
                    ]) ?>
            </div>
        </div>
    </div>
</div>

views/especies/_error.php
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong>¡Error!</strong> <?= $mensaje ?>
</div>

views/especies/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Especies */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="especies-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'especie')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('guardar', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/especies/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EspeciesSearch */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="especies-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'especie')->label('Buca una especie') ?>

    <div class="form-group">
        <?= Html::submitButton('Buscar', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/especies/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Especies */

$this->title = 'Registrar una nueva especie';
$this->params['breadcrumbs'][] = ['label' => 'Especies', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="especies-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/especies/index.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\EspeciesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$url = Url::to(['razas/create']);
$js =<<<EOT
$('.registrar-raza').click((e)=>{
    e.preventDefault();
    var especieId = $(e.target).val();
    var input = $('#input-'+especieId);
    if (input.val() !== '') {
    $.ajax({
            dataType: 'json',
            type: 'post',
            url: "$url",
            data: { raza:input.val(), especie_id: especieId },
            success: (respuesta) => {
                $('.razas-'+especieId).html(respuesta);
            },
            error: (respuesta) => {
                console.log(respuesta)
                var mensaje = `<div class="alert alert-warning alert-dismissible" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <strong>¡Error!</strong> `+respuesta.responseJSON.message+`
                </div>`
                $('.error-'+especieId).html(mensaje);
            }
        });
    }
    input.val('');
});
EOT;
$this->registerJs($js);

$this->title = 'Grupos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="especies-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Registrar nueva especie', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php  echo $this->render('_search', ['model' => $searchModel]); ?>

    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_detalle',
            ]);
        ?>
    </div>


</div>

views/especies/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Especies */

$this->title = 'Actualizar especie: ' . $model->especie;
$this->params['breadcrumbs'][] = ['label' => 'Especies', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->especie, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Actualizar';
?>
<div class="especies-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/especies/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Especies */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Especies', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="especies-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'especie',
        ],
    ]) ?>

</div>