models/Personas.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "personas".
 *
 * @property int $id
 * @property string $nombre
 * @property string $primer_apellido
 * @property string $segundo_apellido
 * @property string $direccion
 * @property string $telefono
 * @property string $email
 * @property string $observaciones
 *
 * @property Acogidas[] $acogidas
 */
class Personas extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'personas';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nombre'], 'required'],
            [['observaciones'], 'string'],
            [['nombre', 'primer_apellido', 'segundo_apellido', 'direccion', 'telefono', 'email'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'primer_apellido' => 'Primer Apellido',
            'segundo_apellido' => 'Segundo Apellido',
            'direccion' => 'Direccion',
            'telefono' => 'Telefono',
            'email' => 'Email',
            'observaciones' => 'Observaciones',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAcogidas()
    {
        return $this->hasMany(Acogidas::className(), ['persona_id' => 'id'])->inverseOf('persona');
    }
}

controllers/PersonasController.php
<?php

namespace app\controllers;

use app\models\Personas;
use app\models\PersonasSearch;
use Yii;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;

/**
 * PersonasController implements the CRUD actions for Personas model.
 */
class PersonasController extends ControllerControlAccess
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                       'allow' => true,
                       'matchCallback' => function ($rule, $action) {
                           return Yii::$app->user->identity !== null && in_array(Yii::$app->user->identity->rol_id, [1, 2]);
                       },
                    ],
                    [
                       'allow' => false,
                       'actions' => ['update', 'delete', 'create', 'view', 'index'],
                       'matchCallback' => function ($rule, $action) {
                           return Yii::$app->user->identity !== null && Yii::$app->user->identity->rol_id == 3;
                       },
                    ],
                ],
            ],
        ];
    }
    /**
     * Lists all Personas models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PersonasSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Personas model.
     * @param int $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Personas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Personas();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Personas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Personas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Personas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id
     * @return Personas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Personas::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/personas/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Personas */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="personas-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'primer_apellido')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'segundo_apellido')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'direccion')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'telefono')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'observaciones')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/personas/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PersonasSearch */
/* @var $form yii\widgets\ActiveForm */
$js = <<<JS
    $('button.avanzado').click((e)=>{
        e.preventDefault();
        $('div.avanzado').toggle(500);
    });
JS;

$this->registerJs($js)
?>

<div class="personas-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'nombre') ?>
<div class="avanzado">

    <?= $form->field($model, 'primer_apellido') ?>

    <?= $form->field($model, 'segundo_apellido') ?>

    <?= $form->field($model, 'direccion') ?>

    <?= $form->field($model, 'telefono') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'observaciones') ?>

</div>
    <div class="form-group">
        <?= Html::submitButton('Buscar', ['class' => 'btn btn-primary']) ?>
        <?= Html::button('Avanzado +',['class' => 'btn avanzado btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/personas/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Personas */

$this->title = 'Registrar adoptante';
$this->params['breadcrumbs'][] = ['label' => 'Personas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="personas-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/personas/index.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PersonasSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Adoptantes';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="personas-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Registrar adoptante', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php  echo $this->render('_search', ['model' => $searchModel]); ?>

    <ul class="cards">
        <?php foreach ($dataProvider->getModels() as $model): ?>
            <li class="cards__item">
                <div class="card">
                    <div class="card__content">
                        <div class="card__title"><?= $model->nombre .' '. $model->primer_apellido .' '. $model->segundo_apellido ?></div>
                        <p class="card__text">
                            Direccion: <?= $model->direccion ?>
                            <br>
                            Telefono: <?= $model->telefono ?>
                            <br>
                            Email: <?= $model->email ?>
                            <br>
                            Observaciones: <?= $model->observaciones ?>
                            <br>
                        </p>
                        <a href="<?= Url::to(['personas/view', 'id' => $model->id]) ?>" class="btn btn--block card__btn btn-default">Ver</a>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>

    </ul>



</div>

views/personas/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Personas */

$this->title = 'Actualizar: ' . $model->nombre .' '. $model->primer_apellido .' '. $model->segundo_apellido;
$this->params['breadcrumbs'][] = ['label' => 'Personas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->nombre .' '. $model->primer_apellido .' '. $model->segundo_apellido, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="personas-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/personas/view.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Personas */

$this->title = 'Adoptante';
$this->params['breadcrumbs'][] = ['label' => 'Personas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="personas-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>

    </p>

    <div class="row">
        <div class="col-sm-5">
            <ul class="cards">
                    <li class="cards__item" >
                        <div class="card" style="width:100%">
                            <div class="card__content">
                                <div class="card__title"><?= $model->nombre .' '. $model->primer_apellido .' '. $model->segundo_apellido ?></div>
                                <p class="card__text">
                                    <?= DetailView::widget([
                                        'model' => $model,
                                        'attributes' => [
                                            'direccion',
                                            'telefono',
                                            'email:email',
                                            'observaciones:ntext',
                                        ],
                                    ]) ?>
                                    <?= Html::a('Actualizar', ['update', 'id' => $model->id], ['class' => 'btn btn--block card__btn btn-default']) ?>
                                    <?= Html::a('Delete', ['Borrar', 'id' => $model->id], [
                                        'class' => 'btn btn-warning',
                                        'data' => [
                                            'confirm' => '¿Estas seguro de borrar esto?',
                                            'method' => 'post',
                                        ],
                                    ]) ?>
                            </div>
                        </div>
                    </li>
            </ul>
        </div>
        <div class="col-sm-5 flex-div center-h center-v">
            <a href="<?= Url::to(['acogidas/create', 'persona_id' => $model->id])  ?>" class="btn btn-lg btn-warning">Adoptar un animal</a>
        </div>
    </div>

    <div class="row">
        <div class=" col-md-12">
            <ul class="cards">
                    <li class="cards__item" >
                        <div class="card" style="width:100%">
                            <div class="card__content">
                                <div class="card__title">Adopciones</div>
                                <p class="card__text">
                                    <table class="table table-hover">
                                        <tr>
                                            <th>Animal</th>
                                            <th>Fecha</th>
                                            <th>Observaciones</th>
                                            <th>Borrar</th>
                                        </tr>
                                        <?php foreach ($model->acogidas as $acogida): ?>
                                            <tr>
                                                <td> <a href="<?= Url::to(['animales/view', 'id' => $acogida->animal->id]) ?>"> <?= $acogida->animal->nombre ?></a></td>
                                                <td><?= Yii::$app->formatter->asDate($acogida->fecha) ?></td>
                                                <td><?= $acogida->observaciones ?></td>
                                                <td><?= Html::a('Borrar', ['acogidas/delete', 'id' => $acogida->id, 'persona_id' => $model->id], [
                                                            'class' => 'btn btn-danger',
                                                            'data' => [
                                                                'confirm' => '¿Sequro que quieres borrar esta adopción?',
                                                                'method' => 'post',
                                                            ],
                                                        ])
                                                    ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </table>
                                </p>
                            </div>
                        </div>
                    </li>
            </ul>
        </div>
    </div>


</div>