models/AnimalesColores.php
<?php

namespace app\models;

/**
 * This is the model class for table "animales_colores".
 *
 * @property int $animal_id
 * @property int $color_id
 *
 * @property Animales $animal
 * @property Colores $color
 */
class AnimalesColores extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'animales_colores';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['animal_id', 'color_id'], 'required'],
            [['animal_id', 'color_id'], 'default', 'value' => null],
            [['animal_id', 'color_id'], 'integer'],
            [['animal_id', 'color_id'], 'unique', 'targetAttribute' => ['animal_id', 'color_id']],
            [['animal_id'], 'exist', 'skipOnError' => true, 'targetClass' => Animales::className(), 'targetAttribute' => ['animal_id' => 'id']],
            [['color_id'], 'exist', 'skipOnError' => true, 'targetClass' => Colores::className(), 'targetAttribute' => ['color_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'animal_id' => 'Animal ID',
            'color_id' => 'Color ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAnimal()
    {
        return $this->hasOne(Animales::className(), ['id' => 'animal_id'])->inverseOf('animalesColores');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getColor()
    {
        return $this->hasOne(Colores::className(), ['id' => 'color_id'])->inverseOf('animalesColores');
    }
}

controllers/AnimalesColoresController.php
<?php

namespace app\controllers;

use app\models\Animales;
use app\models\AnimalesColores;
use app\models\AnimalesColoresSearch;
use Yii;
use yii\web\NotFoundHttpException;

/**
 * AnimalesColoresController implements the CRUD actions for AnimalesColores model.
 */
class AnimalesColoresController extends ControllerControlAccess
{
    /**
     * Lists all AnimalesColores models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AnimalesColoresSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single AnimalesColores model.
     * @param int $animal_id
     * @param int $color_id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($animal_id, $color_id)
    {
        return $this->render('view', [
            'model' => $this->findModel($animal_id, $color_id),
        ]);
    }

 /**
  * Agrega un color a un animal
  * @param  int $animal_id Id del animal
  * @return mixed            Vista animales-colores/update
  */
    public function actionAgregarColores($animal_id)
    {
        $model = Animales::findOne($animal_id);

        if ($model === null) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }


    /**
     * Creates a new AnimalesColores model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new AnimalesColores([
            'animal_id' => Yii::$app->request->post('list'),
            'color_id' => Yii::$app->request->post('item'),
        ]);

        if (!$model->save()) {
            throw new \Exception('No se ha ppodido agregar el color al animal', 1);
        }
    }

    /**
     * Updates an existing AnimalesColores model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $animal_id
     * @param int $color_id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($animal_id, $color_id)
    {
        $model = $this->findModel($animal_id, $color_id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'animal_id' => $model->animal_id, 'color_id' => $model->color_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing AnimalesColores model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete()
    {
        extract(Yii::$app->request->post());
        $this->findModel($list, $item)->delete();
    }

    /**
     * Finds the AnimalesColores model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $animal_id
     * @param int $color_id
     * @return AnimalesColores the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($animal_id, $color_id)
    {
        if (($model = AnimalesColores::findOne(['animal_id' => $animal_id, 'color_id' => $color_id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/animales-colores/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\AnimalesColores */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="animales-colores-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'animal_id')->textInput() ?>

    <?= $form->field($model, 'color_id')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/animales-colores/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\AnimalesColoresSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="animales-colores-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'animal_id') ?>

    <?= $form->field($model, 'color_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/animales-colores/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\AnimalesColores */

$this->title = 'Create Animales Colores';
$this->params['breadcrumbs'][] = ['label' => 'Animales Colores', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="animales-colores-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/animales-colores/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AnimalesColoresSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Animales Colores';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="animales-colores-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Animales Colores', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'animal_id',
            'color_id',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/animales-colores/update.php
<?php

use app\components\Sortable;

use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\AnimalesColores */

$this->title = 'Update Animales Colores: ' . $model->nombre;
$this->params['breadcrumbs'][] = ['label' => 'Animales Colores', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->nombre, 'url' => ['view', 'animal_id' => $model->nombre, 'color_id' => $model->nombre]];
$this->params['breadcrumbs'][] = 'Update';
?>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<div class="animales-colores-update">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= Sortable::widget([
            'view' => $this,
            'list_id' => $model->id,
            'item_view' => '/colores/_color',
            'sortable1' => [
                'accion' => Url::to(['animales-colores/create']) ,
                'items' => $model->colors,
            ],
            'sortable2' => [
                'accion' => Url::to(['animales-colores/delete']) ,
                'items' => $model->getColoresQueNoTengo(),
            ],
        ])
    ?>

    <div class="">
        <?= Html::a('He terminado', ['animales/view', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
        <?= Html::a('Añadir imágenes', ['animales/upload', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
    </div>

</div>

views/animales-colores/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\AnimalesColores */

$this->title = $model->animal_id;
$this->params['breadcrumbs'][] = ['label' => 'Animales Colores', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="animales-colores-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'animal_id' => $model->animal_id, 'color_id' => $model->color_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'animal_id' => $model->animal_id, 'color_id' => $model->color_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'animal_id',
            'color_id',
        ],
    ]) ?>

</div>