models/Animales.php
<?php

namespace app\models;

/**
 * This is the model class for table "animales".
 *
 * @property int $id
 * @property int $especie_id
 * @property string $nombre
 * @property string $nacimiento
 * @property string $defuncion
 * @property string $chip
 * @property string $peso
 * @property bool $ppp
 * @property bool $esterilizado
 * @property string $sexo
 * @property string $observaciones
 * @property string $created_at
 * @property string $updated_at
 *
 * @property Acogidas[] $acogidas
 * @property AnimalesColores[] $animalesColores
 * @property Colores[] $colors
 * @property AnimalesEnfermedades[] $animalesEnfermedades
 * @property AnimalesRazas[] $animalesRazas
 * @property Razas[] $razas
 */
class Animales extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'animales';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nombre', 'especie_id'], 'required'],
            [[
                'nombre',
                'chip',
                'peso',
                'nacimiento',
                'defuncion',
                'sexo',
                'chip',
                'ppp',
                'observaciones',
            ], 'trim'],

            [[
                'chip',
                'sexo',
                'chip',
            ], 'filter', 'filter' => 'strtolower'],
            [[
                'nombre',
                'chip',
                'nacimiento',
                'defuncion',
                'sexo',
                'chip',
            ], 'filter', 'filter' => function ($value) {
                return str_replace('.', '', $value);
            }],
            [['sexo'], 'match', 'pattern' => '/^[h|m]{1}$/'],
            [['nacimiento', 'chip', 'peso', 'sexo'], 'default', 'value' => null],
            [['peso'], 'number', 'min' => 0, 'max' => 9999],
            [['ppp', 'esterilizado'], 'boolean'],
            [['observaciones'], 'string'],
            [['nombre', 'chip', 'defuncion'], 'string', 'max' => 255],
            [['sexo'], 'string', 'max' => 6],
            [['chip'], 'unique'],
            [['especie_id'], 'integer'],
            [['especie_id'], 'exist', 'skipOnError' => true, 'targetClass' => Especies::className(), 'targetAttribute' => ['especie_id' => 'id']],
            ['especie_id', function ($attribute, $params, $validator) {
                $razasDiscordantes = AnimalesRazas::find()->joinWith('raza')->where(['animal_id' => $this->id])->andWhere(['<>', 'especie_id', $this->especie_id])->all();
                foreach ($razasDiscordantes as $animal_raza) {
                    $animal_raza->delete();
                }
            }],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'nacimiento' => 'Nacimiento',
            'chip' => 'Chip',
            'peso' => 'Peso',
            'ppp' => 'PPP',
            'esterilizado' => 'Esterilizado',
            'sexo' => 'Sexo',
            'especie_id' => 'Especie',
            'observaciones' => 'Observaciones',
            'defuncion' => 'Fecha defunción',
            'created_at' => 'Fecha Creación',
            'updated_at' => 'Última modificación',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEspecie()
    {
        return $this->hasOne(Especies::className(), ['id' => 'especie_id'])->inverseOf('animales');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTratamientos()
    {
        return $this->hasMany(Tratamientos::className(), ['animal_id' => 'id'])->inverseOf('animal');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMedicamentos()
    {
        return $this->hasMany(Medicamentos::className(), ['id' => 'medicamento_id'])->viaTable('tratamientos', ['animal_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAcogidas()
    {
        return $this->hasMany(Acogidas::className(), ['animal_id' => 'id'])->inverseOf('animal');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAnimalesColores()
    {
        return $this->hasMany(AnimalesColores::className(), ['animal_id' => 'id'])->inverseOf('animal');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getColors()
    {
        return $this->hasMany(Colores::className(), ['id' => 'color_id'])->viaTable('animales_colores', ['animal_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAnimalesEnfermedades()
    {
        return $this->hasMany(AnimalesEnfermedades::className(), ['animal_id' => 'id'])->inverseOf('animal')->orderBy('desde', 'ASC');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAnimalesRazas()
    {
        return $this->hasMany(AnimalesRazas::className(), ['animal_id' => 'id'])->inverseOf('animal');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRazas()
    {
        return $this->hasMany(Razas::className(), ['id' => 'raza_id'])->viaTable('animales_razas', ['animal_id' => 'id']);
    }

    /**
     * sexos disponibles de un animal
     * @return array los sexos disponibles.
     */
    public function sexosDisponibles()
    {
        return [
            '' => '',
            'h' => 'HEMBRA',
            'm' => 'MACHO',
        ];
    }

    /**
    * Colores que no tiene el animal
    * @return array Array con los modelos de razas.
    */

    public function getColoresQueNoTengo()
    {
        // if (!isset($this->sintomasQueNoTengo)) {
        //     return $this->sintomasQueNoTengo;
        // }
        $sql = <<<'EOT'
select *
  from colores
except
select colores.*
  from colores
  join animales_colores
    on colores.id = animales_colores.color_id
 where animales_colores.animal_id = :animal_id
EOT;
        return Colores::findBySql($sql, [':animal_id' => $this->id])->all();
    }

    /**
    * Razas a las que no pertenece el animal
    * @return array Array con los modelos de razas.
    */

    public function getRazasQueNoTengo()
    {
        // if (!isset($this->sintomasQueNoTengo)) {
        //     return $this->sintomasQueNoTengo;
        // }
        $sql = <<<'EOT'
select *
  from Razas
where especie_id = :especie_id
except
select Razas.*
  from razas
  join animales_razas
    on razas.id = animales_razas.raza_id
 where animales_razas.animal_id = :animal_id
   and especie_id = :especie_id
EOT;
        return Razas::findBySql($sql, [':animal_id' => $this->id, ':especie_id' => $this->especie_id])->all();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVacunaciones()
    {
        return $this->hasMany(Vacunaciones::className(), ['animal_id' => 'id'])->inverseOf('animal')->orderBy('vacunaciones.fecha');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVacunas()
    {
        return $this->hasMany(Vacunas::className(), ['id' => 'medicamento_id'])->viaTable('vacunaciones', ['animal_id' => 'id'])->orderBy('vacunas.vacuna');
    }
}

controllers/AnimalesController.php
<?php

namespace app\controllers;

use app\models\Acogidas;
use app\models\Animales;
use app\models\AnimalesColores;
use app\models\AnimalesEnfermedades;
use app\models\AnimalesRazas;
use app\models\AnimalesSearch;
use app\models\Especies;
use app\models\Medicamentos;
use app\models\Tratamientos;
use app\models\Vacunaciones;
use app\models\Vacunas;
use Yii;
use yii\helpers\Url;
use yii\httpclient\Client;
use yii\web\NotFoundHttpException;

/**
 * AnimalesController implements the CRUD actions for Animales model.
 */
class AnimalesController extends ControllerControlAccess
{
    /**
     * Lists all Animales models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AnimalesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);


        return $this->render('index', [
            'especies' => Especies::todas(),
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Animales model.
     * @param int $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $imagenes = $this->getImagenes($model->id);

        return $this->render('view', [
            'model' => $model,
            'imagenes' => $imagenes,
            'tratamiento' => new Tratamientos(['animal_id' => $model->id]),
            'listaMedicamentos' => Medicamentos::todas(),
            'vacunacion' => new Vacunaciones(['animal_id' => $model->id]),
            'vacunas' => Vacunas::todas(),
        ]);
    }

    /**
     * Creates a new Animales model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Animales();


        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $client = new Client(['baseUrl' => 'http://104.248.139.77/web']);
            $response = $client->get("grupos/{$model->id}")->send();
            if ($response->getData() == null) {
                $client = new Client(['baseUrl' => 'http://104.248.139.77/web']);
                $response = $client->post('grupos', ['nombre' => $model->id])->send();
            }
            return $this->redirect(Url::to(['/animales-razas/agregar-razas', 'animal_id' => $model->id, 'especie_id' => $model->especie_id]));
        }

        return $this->render('create', [
            'model' => $model,
            'especies' => Especies::todas(),
        ]);
    }


    /**
     * Updates an existing Animales model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(Url::to(['/animales-razas/agregar-razas', 'animal_id' => $model->id, 'especie_id' => $model->especie_id]));
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'especies' => Especies::todas(),
        ]);
    }

    /**
     * Deletes an existing Animales model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $animal = $this->findModel($id);
        Acogidas::deleteAll(['animal_id' => $animal->id]);
        AnimalesColores::deleteAll(['animal_id' => $animal->id]);
        AnimalesRazas::deleteAll(['animal_id' => $animal->id]);
        AnimalesEnfermedades::deleteAll(['animal_id' => $animal->id]);

        $client = new Client();
        $response = $client->createRequest()
        ->setMethod('DELETE')
        ->setUrl("http://104.248.139.77/web/grupos/{$model->id}")
        ->send();

        $animal->delete();

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Envia al servicio de almacenamiento la imagenes subidas
     * @param  int $id id del modelo al que corresponden las imágenes
     * @return mixed     Devuelve la vista del modelo
     */

    public function actionUpload($id)
    {
        $model = Animales::findOne(['id' => $id]);

        if (!empty($_POST)) {
            $client = new Client();
            $request = $client->createRequest()
                ->setMethod('PUT')
                ->setUrl("http://104.248.139.77/web/grupos/{$id}");

            foreach ($_FILES['imagenes']['tmp_name'] as $key => $file) {
                $request = $request->addFile("upfile[{$key}]", $file);
            }

            $response = $request->send();

            return $this->redirect(Url::to(['/animales/view', 'id' => $id]));
        }

        return $this->render('upload-imagenes', [
            'model' => $model,
        ]);
    }

    /**
     * Coge  las imagenes referentes a un modelo
     * @param  int $id id del modelo
     * @return mixed     devuelve la vista imagenes
     */

    public function actionGestionarImagenes($id)
    {
        $model = $this->findModel($id);
        $imagenes = $this->getImagenes($model->id);

        return $this->render('imagenes', [
            'model' => $model,
            'imagenes' => $imagenes,
        ]);
    }

    /**
     * Establece el avatar de un animal
     * @param  int $id  id del animal
     * @param  int $url url de la imagen
     * @return mixed      redirige a la vista del animal
     */

    public function actionAvatar($id, $url)
    {
        $model = $this->findModel($id);
        $model->avatar = $url;
        if ($model->save()) {
            Yii::$app->session->setFlash('success', 'Se ha cambiado el avatar correctamente');
        } else {
            Yii::$app->session->setFlash('error', 'No se ha podido llevar a cabo la acción');
        }
        return $this->redirect(['animales/view', 'id' => $id]);
    }

    /**
     * Borra una imagen a traves de una api
     * @param  int $id        id del modelo a la que pertenece ña imagen
     * @param  int $imagen_id id de la imagen
     * @return mixed            Devuelve una vista
     */

    public function actionBorrarImagen($id, $imagen_id)
    {
        $model = $this->findModel($id);

        $client = new Client(['baseUrl' => 'http://104.248.139.77/web']);
        $response = $client->delete("images/{$imagen_id}")->send();
        if ($response->getData() === 1) {
            Yii::$app->session->setFlash('success', 'Se ha borrado correctamente');
        } else {
            Yii::$app->session->setFlash('error', 'No se ha borrado la imagen');
        }

        $imagenes = $this->getImagenes($model->id);

        return $this->render('imagenes', [
            'model' => $model,
            'imagenes' => $imagenes,
        ]);
    }

    /**
     * Actualiza el estado de un animal
     * @return int valor de referencia
     * @throws  NotFoundHttpException if the model cannot be found
     */

    public function actionDefuncion()
    {
        $model = $this->findModel(Yii::$app->request->post('id'));
        if ($model->defuncion === null) {
            $model->defuncion = date('Y-m-d');
        } else {
            $model->defuncion = null;
        }
        if ($model->save()) {
            return 0;
        }
        throw new \Exception('Error Processing Request', 1);
    }

    /**
     * Finds the Animales model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id
     * @return Animales the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Animales::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Devuelve las rutas de las imagenes asocuados a un modelo
     * @param  int $id id del modelo
     * @return array     Array con las rutas
     */

    protected function getImagenes($id)
    {
        $client = new Client(['baseUrl' => 'http://104.248.139.77/web']);
        $response = $client->get("grupos/{$id}")->send();
        return $response->getData();
    }
}

views/animales/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
use kartik\number\NumberControl;

/* @var $this yii\web\View */
/* @var $model app\models\Animales */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="animales-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-sm-3">
            <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-sm-3">
            <?= $form->field($model, 'peso')->widget(NumberControl::class, [
                'maskedInputOptions' => [
                    'suffix' => ' Kg',
                    'allowMinus' => false,
                    'groupSeparator' => '',
                    'radixPoint' => ',',
                    'min' => 0,
                    'max' => 9999,
                ],
            ])
            ?>
        </div>
        <div class="col-sm-3">
            <?= $form->field($model, 'nacimiento')->widget(DatePicker::className(), [
                'type' => DatePicker::TYPE_COMPONENT_APPEND,
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'yyyy-mm-dd'
                ]
                ]) ?>
        </div>
        <div class="col-sm-3">
            <?= $form->field($model, 'especie_id')->dropDownList($especies) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <?= $form->field($model, 'chip')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-sm-12 flex center-h">
            <?= $form->field($model, 'ppp')->checkbox() ?>
        </div>
        <div class="col-sm-12 flex center-h">
            <?= $form->field($model, 'esterilizado')->checkbox() ?>
        </div>
        <div class="col-sm-12 flex center-h">
            <?= $form->field($model, 'sexo')->radioList([
                'h' => 'Hembra',
                'm' => 'Macho',
                ]) ?>
        </div>

    </div>
    <?= $form->field($model, 'observaciones')->textarea(['rows' => 3]) ?>

    <div class="form-group  flex center-h">
        <?= Html::submitButton('Siguiente >', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/animales/_search.php
<?php

use kartik\date\DatePicker;

use kartik\number\NumberControl;

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\AnimalesSearch */
/* @var $form yii\widgets\ActiveForm */

$js = <<<JS
    $('button.avanzado').click((e)=>{
        e.preventDefault();
        $('div.avanzado').toggle(500);
    });
JS;

$this->registerJs($js)
?>

<div class="animales-search">

    <?php $form = ActiveForm::begin([
        'action' => isset($url) ? $url : ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'nombre') ?>
<div class="avanzado">

    <?= $form->field($model, 'chip') ?>
    <div class="row">
        <fieldset>
            <legend>Nacimiento</legend>
            <div class="col-sm-6">
                <?= $form->field($model, 'nacimiento_desde')->widget(DatePicker::className(), [
                    'type' => DatePicker::TYPE_COMPONENT_APPEND,
                    'pluginOptions' => [
                        'autoclose'=>true,
                        'format' => 'yyyy-mm-dd'
                    ]
                    ])->label('Desde') ?>
                </div>
                <div class="col-sm-6">
                    <?= $form->field($model, 'nacimiento_hasta')->widget(DatePicker::className(), [
                        'type' => DatePicker::TYPE_COMPONENT_APPEND,
                        'pluginOptions' => [
                            'autoclose'=>true,
                            'format' => 'yyyy-mm-dd'
                        ]
                        ])->label('Hasta') ?>
                    </div>
                </fieldset>
            </div>


            <div class="row">
                <fieldset>
                    <legend>Peso</legend>
                    <div class="col-sm-6">
                        <?= $form->field($model, 'peso_desde')->widget(NumberControl::class, [
                            'maskedInputOptions' => [
                                'suffix' => ' Kg',
                                'allowMinus' => false,
                                'groupSeparator' => '',
                                'radixPoint' => ',',
                                'min' => 0,
                                'max' => 9999,
                            ],
                            ])->label('Desde') ?>
                        </div>

                        <div class="col-sm-6">
                            <?= $form->field($model, 'peso_hasta')->widget(NumberControl::class, [
                                'maskedInputOptions' => [
                                    'suffix' => ' Kg',
                                    'allowMinus' => false,
                                    'groupSeparator' => '',
                                    'radixPoint' => ',',
                                    'min' => 0,
                                    'max' => 9999,
                                ],
                                ])->label('Hasta') ?>
                            </div>
                        </fieldset>
                    </div>
                    <div class="row">
                        <div class="col-sm-3">
                            <?= $form->field($model, 'ppp')->dropDownList([
                                '' => '',
                                '1' => 'PPP',
                                '0' => 'NO PPP',
                            ])
                            ?>
                        </div>
                        <div class="col-sm-3">
                            <?= $form->field($model, 'esterilizado')->dropDownList([
                                '' => '',
                                '1' => 'Esterilizado',
                                '0' => 'NO Esterilizado',
                            ])
                            ?>
                        </div>
                        <div class="col-sm-3">
                            <?php echo $form->field($model, 'sexo')->dropDownList($model->sexosDisponibles()) ?>
                        </div>
                        <div class="col-sm-3">
                            <?php $especies = ['' => ''] + $especies ?>
                            <?= $form->field($model, 'especie')->dropDownList($especies)->label('Grupo')?>
                        </div>
                        <div class="col-sm-3">
                            <?= $form->field($model, 'adoptado')->checkbox()->label('Adoptado')?>
                        </div>
                    </div>

                    <?php echo $form->field($model, 'observaciones') ?>

                    <?php // echo $form->field($model, 'created_at') ?>

                    <?php // echo $form->field($model, 'updated_at') ?>

                </div>
                    <div class="form-group">
                        <?= Html::submitButton('Buscar', ['class' => 'btn btn-primary']) ?>
                        <?= Html::button('Avanzado +',['class' => 'btn avanzado btn-default']) ?>
                    </div>

                    <?php ActiveForm::end(); ?>

                </div>

views/animales/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Animales */

$this->title = 'Registrar un animal';
$this->params['breadcrumbs'][] = ['label' => 'Animales', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="animales-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'especies' => $especies,
    ]) ?>

</div>

views/animales/imagenes.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AnimalesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Gestionar Imágenes';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="animales-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <a class="btn btn-default" href="<?= Url::to(['animales/upload', 'id' => $model->id]) ?>">Agregar imágenes</a>
    <a class="btn btn-default" href="<?= Url::to(['animales/view', 'id' => $model->id]) ?>">volver</a>
    <ul class="cards">
        <?php foreach ($imagenes as $imagen): ?>
            <li class="cards__item">
                <div class="card">
                    <div class="card__image card__image--flowers"><img src="http://<?= $imagen ?>" alt="Imagen de animal"></div>
                    <div class="card__content">
                        <?= Html::a('Hacer Avatar', ['avatar', 'id' => $model->id, 'url' => $imagen], ['class' => 'btn btn--block card__btn btn-default']) ?>
                        <?= Html::a('Borrar', ['animales/borrar-imagen', 'id' => $model->id, 'imagen_id' => substr($imagen,strripos($imagen, '/') + 1)], [
                            'class' => 'btn btn--block card__btn btn-danger',
                            'data' => [
                                'confirm' => '¿Sequro que quieres borrar?',
                                'method' => 'post',
                            ],
                            ]) ?>
                        </div>
                    </div>
                </li>
        <?php endforeach; ?>
    </ul>
</div>

views/animales/index.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AnimalesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Animales';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="animales-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->user->identity->rol_id != 3): ?>
        <p>
            <?= Html::a('Registrar un animal', ['create'], ['class' => 'btn btn-success']) ?>
        </p>
    <?php endif; ?>
    
    <?php
        $parametros =  [
            'model' => $searchModel,
            'especies' => $especies,
        ];
        if (isset($persona)) {
            $parametros['url'] = ['acogidas/create', 'persona_id' => $persona->id];
        }
    ?>
    <?php echo $this->render('_search', $parametros); ?>



<ul class="cards">
    <?php foreach ($dataProvider->getModels() as $model): ?>
        <li class="cards__item">
            <div class="card">
                <div class="card__image card__image--flowers">
                    <a href="<?= Url::to(['animales/view', 'id' => $model->id]) ?>">
                        <img src="http://<?= $model->avatar ?>" alt="">
                    </a>
                </div>
                <div class="card__content">
                    <div class="card__title"><?= $model->nombre ?></div>
                    <p class="card__text">
                        <?php $tipo = ($acogida = $model->getAcogidas()->one()) == null ? 'ACOGIDO' : $acogida->tipo->tipo ?>
                        Estado: <?= $tipo ?><br>
                        Sexo:
                        <?php if ($model->sexo == null): ?>
                            No definido
                        <?php else: ?>
                            <?php if ($model->sexo == 'h'): ?>
                                HEMBRA
                            <?php else: ?>
                                MACHO
                            <?php endif; ?>
                        <?php endif; ?>
                        <br>
                        Esterilizado: <?= Yii::$app->formatter->asBoolean($model->esterilizado) ?>
                        <br>
                        Peso: <?= Yii::$app->formatter->asWeight($model->peso) ?>
                        <br>
                        Grupo: <?= $model->especie->especie ?>
                    </p>
                    <?php if (isset($persona)): ?>
                        <form class="" action="<?= Url::to(['acogidas/create']) ?>" method="post">
                                <input type="hidden" name="<?= Yii::$app->request->csrfParam; ?>" value="<?= Yii::$app->request->csrfToken; ?>" />
                            <input type="hidden" name="persona_id" value="<?= $persona->id ?>">
                            <input type="hidden" name="animal_id" value="<?= $model->id ?>">
                            <input type="hidden" name="fecha" value="<?= \date('Y-m-d') ?>">
                            <textarea name="observaciones" rows="2" cols="20" placeholder="Observaciones sobre la adopción"></textarea>
                            <button class="btn-warning" type="submit">Adoptar por <?= $persona->nombre . ' ' . $persona->primer_apellido ?></button>
                        </form>
                    <?php else: ?>
                        <a href="<?= Url::to(['animales/view', 'id' => $model->id]) ?>" class="btn btn--block card__btn btn-default">Ver</a>
                    <?php endif; ?>
                </div>
            </div>
        </li>
    <?php endforeach; ?>

</ul>


</div>

views/animales/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Animales */

$this->title = 'Actualizar Animal: ' . $model->nombre;
$this->params['breadcrumbs'][] = ['label' => 'Animales', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->nombre, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Actualizar';
?>
<div class="animales-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'especies' => $especies,
    ]) ?>

</div>

views/animales/upload-imagenes.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Animales */

$this->title = 'Agregar imagenes de un animal';
$this->params['breadcrumbs'][] = ['label' => 'Animales', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="animales-create">

    <h1><?= Html::encode($this->title) ?></h1>

<?= Html::beginForm(Url::to(['animales/upload','id' => $model->id]), 'POST', ['enctype' => 'multipart/form-data']) ?>
<?= Html::fileInput('imagenes[]',null,['multiple' => 'multiple', 'accept' => 'image/*']) ?>
<?= Html::submitButton('Guardar') ?>
<?= Html::endForm() ?>

</div>